optimizer:
  lr: 0.01
  momentum: 0.9
  type: Adam
  loss: L1

epoch_num: 10
batch_size: 16
IMAGE_SIZE: (32,32)

show_progress: True

model:
  one_dim: view

mlflow:
  runname: try_mlflow

defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe


hydra: 
  sweeper:
    direction: maximize
    study_name: single_detection
    storage: null # これ何?
    n_trials: 20
    n_jobs: 1
    sampler:
      seed: 123

# hydra: 
#   sweeper:
#     optuna_config:
#       direction: maximize
#       study_name: single_detection
#       storage: null # これ何?
#       n_trials: 20
#       n_jobs: 1
#       seed: 123